### ISSUE TITLE
Incompatible with latest version of Zod

### ISSUE THREAD

**Issue by Lordfirespeed** [alexmarqs/zod-config#12]
I'm getting a TypeScript error with the latest `zod-config` and `zod@3.23.8`:
```
src/config/index.ts(12,3): error TS2322: Type 'ZodObject<{ listen: ZodObject<{ host: ZodString; port: ZodNumber; }, "strip", ZodTypeAny, { host: string; port: number; }, { host: string; port: number; }>; ... 5 more ...; mailgun: ZodObject<...>; }, "strip", ZodTypeAny, { ...; }, { ...; }>' is not assignable to type 'AnyZodObject'.
  Types have separate declarations of a private property '_cached'.
```

```ts
const config = await loadConfig({
  schema: configSchema,
       /* ^^^^^^^^^^^^ the error is here */
  adapters: directoryAdapter({
    paths: path.join(dirname, "..", "config"),
    adapters: [
      {
        extensions: [".ts", ".js"],
        adapterFactory: (filePath: string) => scriptAdapter({ path: filePath }),
      },
    ],
  }),
})
```

Looks like the type signature for `AnyZodObject` changed slightly in the backend between `zod@3.22.4` and `zod@3.23.8` 😓

**Comment by alexmarqs** [comment]
Hi @Lordfirespeed can you send me the configSchema used as well?

**Comment by alexmarqs** [comment]
Hi @Lordfirespeed, just quickly checked and I'm using `"zod": "3.23.8",
"zod-config": "0.0.5"` + typescript 5.xxx in a project and I'm not getting the type error 🤔 Can you point me to a repro branch for example? tks!

**Comment by Lordfirespeed** [comment]
Blimey, it was late when I posted this but I must have worded it wrong because I remember **resolving** the issue by updating zod to latest 😂 
I'll try to figure out what caused the issue :)

**Comment by Lordfirespeed** [comment]
Here's what I think happened - 
- was working on my feature branch (#11)
- encountered an issue with typescript not importing types 
- switched module resolution to `bundler` to resolve the issue
- switched `module` to `esnext` to allow module resolution to be `bundler`
- ran `build`
- `pnpm link`ed my local project into another project to test
- encountered the issue
- ran `pnpm i zod@latest` in zod-config and rebuilt
- issue was resolved
